package com.backend.entities;


import com.backend.entities.IDs.AccountID;

import java.sql.Timestamp;

public class Invitation {
    // The value is generated by Account.java
    private final AccountID senderID;

    // The value is generated by Account.java
    private final AccountID receiverID;

    private final Timestamp timestamp;

    // fields, getters
    public Invitation(AccountID senderID, AccountID receiverID, Timestamp timestamp) {
        this.senderID = senderID;
        this.receiverID = receiverID;
        this.timestamp = timestamp;
    }

    public AccountID getSenderID() {
        return this.senderID;
    }

    public AccountID getReceiverID() {
        return this.receiverID;
    }

    public Timestamp getTimestamp() {
        return this.timestamp;
    }
}
