package com.backend.entities;


import com.backend.entities.IDs.AccountID;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.Document;

import java.sql.Timestamp;
import java.util.Date;

@Document(collection = "InvitationsCollection")
public class Invitation {
    // The value is generated by Account.java
    @Transient
    @JsonIgnore
    private final AccountID senderIDObject;

    // The value is generated by Account.java
    @Transient
    @JsonIgnore
    private final AccountID receiverIDObject;

    @Id
    private final String ID;

    private final String senderID;
    private final String receiverID;


    private final Date timestamp;

    // fields, getters

    public Invitation(String senderID, String receiverID, Date timestamp) {
        this.ID = senderID + receiverID;
        this.senderIDObject = new AccountID(senderID);
        this.receiverIDObject = new AccountID(receiverID);
        this.senderID = this.senderIDObject.toString();
        this.receiverID = this.receiverIDObject.toString();
        this.timestamp = timestamp;
    }
    @PersistenceCreator
    public Invitation(String ID, String senderID, String receiverID, Date timestamp) {
        this.ID = ID;
        this.senderIDObject = new AccountID(senderID);
        this.receiverIDObject = new AccountID(receiverID);
        this.senderID = this.senderIDObject.toString();
        this.receiverID = this.receiverIDObject.toString();
        this.timestamp = new Timestamp(timestamp.getTime());
    }

    public AccountID getSenderIDObject() {
        return this.senderIDObject;
    }

    public AccountID getReceiverIDObject() {
        return this.receiverIDObject;
    }

    public String getSenderID(){
        return this.senderID;
    }

    public String getReceiverID(){
        return this.receiverID;
    }

    public Timestamp getTimestamp() {
        if(timestamp == null) {
            return null;
        }
        return new Timestamp(timestamp.getTime());
    }
}
