package Entity;

public class Invitations {
    @senderID
    // The value is generated by Account.java
    private String senderID;

    @receiverID
    // The value is generated by Account.java
    private String receiverID;

    @Transient
    private String timestamp;

    // fields, getters, and setters

    public Invitations(String senderID, String receiverID, String timestamp) {
        this.senderID = senderID;
        this.receiverID = receiverID;
        this.timestamp = timestamp;
    }

    public String getSenderID() {return this.senderID;}
    public String getReceiverID() {return this.receiverID;}

}
